# Generated by Django 2.0.1 on 2018-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=264)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
