# Generated by Django 2.0.1 on 2018-02-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
