# Generated by Django 2.0.1 on 2018-02-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0004_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_number',
        ),
    ]
