# Generated by Django 2.0.1 on 2018-02-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0005_remove_contactinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adress_book.ContactInfo'),
        ),
    ]
