# Generated by Django 2.0.1 on 2018-02-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0006_auto_20180217_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='user_id',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='adress_book.UserData'),
        ),
    ]
