# Generated by Django 2.0.1 on 2018-02-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adress_book', '0012_auto_20180218_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
